### ISSUE TITLE
Primer Commit Videojoc WEB

### ISSUE THREAD

**Issue by u1979253** [FullStackDevUDG/GalacticTweet#1]

**Comment by u1979261** [comment]
Des d'un inici vam començar a elaborar el joc en grup compartint-nos la carpeta del joc principal entre nosaltres. Avui ens vam adonar que havíem de pujar-ho al GitHub, part del joc, ja està fet, hem creat el moviment de l'ocell, el Spawn dels obstacles, hem creat 2 obstacles, un bo i un dolent i hem creat un menú. El que queda per modificar ara, és arreglar l'options del menú, fer que quan el jugador mori se li avisi i torni al menú principal i afegir el logo.
